/Users/guyma/Library/Python/3.11/lib/python/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/guyma/code/projects/lynnapse-scraper/lynnapse/__init__.py", line 10, in <module>
    from .core import *
  File "/Users/guyma/code/projects/lynnapse-scraper/lynnapse/core/__init__.py", line 32, in <module>
    from .adaptive_faculty_crawler import AdaptiveFacultyCrawler
  File "/Users/guyma/code/projects/lynnapse-scraper/lynnapse/core/adaptive_faculty_crawler.py", line 25, in <module>
    from .llm_assistant import LLMAssistant
ImportError: cannot import name 'LLMAssistant' from 'lynnapse.core.llm_assistant' (/Users/guyma/code/projects/lynnapse-scraper/lynnapse/core/llm_assistant.py)
